include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    constant_identifier_names: ignore
    library_prefixes: ignore
    non_constant_identifier_names: ignore
    prefer_final_fields: ignore
