import 'package:chat/models/profile.model.dart';

ProfileModel fromJsonToProfile(Map<String, dynamic> json) {
  return ProfileModel(
    id: json['user']['id'].toString(),
    status: json['user']['status'].toLowerCase(),
    avatar: json['user']['avatar'],
    defaultAvatar: json['user']['default_avatar'],
    fullname: json['user']['name'],
    last: json['user']['formatted_last_activity'],
    lastAt: DateTime.parse(json['user']['last_activity']),
    seen: json['user']['online'].toString().toLowerCase(),
    age: json['user']['age'],
    phone: json['user']['mobile_phone'],
    verified: json['user']['mobile_phone_active'],
    birthDate: json['user']['formatted_birth_date'],
    registerDate: json['user']['formatted_created_at'],
    education: json['user_titles']['education'],
    religion: json['user_titles']['religion'],
    marriageType: json['user_titles']['marriageType'],
    gender: json['user_titles']['gender'],
    marital: json['user_titles']['marital'],
    color: json['user_titles']['color'],
    beauty: json['user_titles']['beauty'],
    shape: json['user_titles']['shape'],
    house: json['user_titles']['home'],
    salary: json['user_titles']['salary'],
    car: json['user_titles']['car'],
    health: json['user_titles']['health'],
    living: json['user_titles']['living'],
    province: json['user_titles']['province'],
    city: json['user_titles']['city'],
    children: json['user_titles']['children'],
    childMaxAge: json['user_titles']['maxAge'],
    height: json['user_titles']['height'],
    weight: json['user_titles']['weight'],
    job: json['user']['job'],
    about: json['user']['about'],
    reports: 0,
    plan: Plan(
      free: json['user']['plan']['free'],
      freeHours: json['user']['plan']['free_hours'],
      freeMinutes: json['user']['plan']['free_minutes'],
      special: json['user']['plan']['special'],
      specialDays: json['user']['plan']['special_days'],
      ad: json['user']['plan']['ad'],
      adDays: json['user']['plan']['ad_days'],
      sms: json['user']['plan']['sms'] ?? 0,
    ),
    permission: json['settings'] == null
        ? Permission(
            voiceCall: false,
            videoCall: false,
            notificationReaction: false,
            notificationChat: false,
            notificationVoiceCall: false,
            notificationVideoCall: false,
          )
        : Permission(
            videoCall: json['settings']['allowVideoCall'],
            voiceCall: json['settings']['allowVoiceCall'],
            notificationChat: json['settings']['notificationChat'],
            notificationReaction: json['settings']['notificationReaction'],
            notificationVideoCall: json['settings']['notificationVideoCall'],
            notificationVoiceCall: json['settings']['notificationVoiceCall'],
          ),
    relation: Relation(
      blocked: json['user']['my_reactions']?['blocked'] ?? false,
      blockedMe: json['user']['user_reactions']?['blocked'] ?? false,
      favorited: json['user']['my_reactions']?['faved'] ?? false,
      liked: json['user']['my_reactions']?['like'] ?? false,
      disliked: json['user']['my_reactions']?['dislike'] ?? false,
    ),
    relationCount: json['user']['reactions_count'] == null
        ? RelationCount(likes: 0, dislikes: 0)
        : RelationCount(
            likes: json['user']['reactions_count']['likes'],
            dislikes: json['user']['reactions_count']['dislikes'],
          ),
    dropdowns: {
      "marriageType": json['user']['marriageType'],
      "religion": json['user']['religion'],
      "city": json['user']['city'],
      "province": json['user']['province'],
      "house": json['user']['home'],
      "home": json['user']['home'],
      "car": json['user']['car'],
      "salary": json['user']['salary'],
      "living": json['user']['living'],
      "education": json['user']['education'],
      "health": json['user']['health'],
      "beauty": json['user']['beauty'],
      "shape": json['user']['shape'],
      "color": json['user']['color'],
      "weight": json['user']['weight'],
      "height": json['user']['height'],
      "maxAge": json['user']['maxAge'],
      "children": json['user']['children'],
      "marital": json['user']['marital'],
      "day": json['user']['day'],
      "month": json['user']['month'],
      "year": json['user']['year'],
      "gender": json['user']['gender'],
    },
    permissions: json['user']['permissions'] == null
        ? []
        : (json['user']['permissions'] as List)
            .map((e) => e.toString())
            .toList(),
  );
}
